# Generated by Django 5.2.3 on 2026-03-24 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_threads', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('company', 'student')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.messagethread')),
            ],
            options={
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='MicroInternship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('primary_role', models.CharField(choices=[('Engineering', [('software_eng', 'Software Engineer'), ('mobile_dev', 'Mobile Developer'), ('frontend_eng', 'Frontend Engineer'), ('backend_eng', 'Backend Engineer'), ('fullstack_eng', 'Full-Stack Engineer'), ('machine_learning', 'Machine Learning Engineer')]), ('Design', [('uiux_designer', 'UI/UX Designer'), ('product_designer', 'Product Designer'), ('graphic_designer', 'Graphic Designer')]), ('Operations', [('hr', 'H.R.'), ('finance', 'Finance/Accounting'), ('ops_manager', 'Operations Manager')]), ('Sales/Marketing', [('business_dev', 'Business Development'), ('marketing_mgr', 'Marketing Manager'), ('content_creator', 'Content Creator')])], default='software_eng', max_length=50)),
                ('type_of_position', models.CharField(choices=[('FT', 'Full-time Employee'), ('CON', 'Contractor'), ('COF', 'Cofounder'), ('INT', 'Intern')], default='INT', max_length=10)),
                ('work_experience', models.CharField(max_length=100)),
                ('skills_required', models.TextField(blank=True, help_text='Comma separated skills')),
                ('location', models.CharField(max_length=255)),
                ('remote_work_details', models.CharField(choices=[('OFF', 'In Office'), ('ONS', 'Onsite'), ('REM', 'Remote'), ('REMO', 'Remote Only')], default='OFF', max_length=10)),
                ('salary', models.CharField(max_length=100)),
                ('equity', models.CharField(blank=True, max_length=100, null=True)),
                ('company_size', models.CharField(choices=[('1-10', '1-10 Employees'), ('11-50', '11-50 Employees'), ('51-200', '51-200 Employees'), ('501+', '501+ Employees')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internships', to=settings.AUTH_USER_MODEL)),
                ('primary_recruiting_contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_jobs', to=settings.AUTH_USER_MODEL)),
                ('subscribers', models.ManyToManyField(blank=True, related_name='subscribed_jobs', to=settings.AUTH_USER_MODEL)),
                ('tagged_coworkers', models.ManyToManyField(blank=True, related_name='tagged_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='resumes/')),
                ('motivation', models.TextField(blank=True, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('availability', models.CharField(blank=True, max_length=100, null=True)),
                ('portfolio', models.URLField(blank=True, null=True)),
                ('skills', models.CharField(blank=True, max_length=255)),
                ('cover_letter', models.TextField(blank=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_shortlisted', models.BooleanField(default=False)),
                ('match_score', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.microinternship')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('company', 'Company')], max_length=10)),
                ('university', models.CharField(blank=True, max_length=255, null=True)),
                ('major', models.CharField(blank=True, max_length=255, null=True)),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('gpa', models.CharField(blank=True, max_length=10, null=True)),
                ('profile_completed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
