# Generated by Django 5.2.3 on 2026-03-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='microinternship',
            name='duration',
            field=models.PositiveIntegerField(default=4, help_text='Duration in weeks'),
        ),
    ]
