# Generated by Django 5.2.3 on 2026-03-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_microinternship_primary_recruiting_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microinternship',
            name='salary',
        ),
        migrations.AddField(
            model_name='microinternship',
            name='max_salary',
            field=models.PositiveIntegerField(default=0, help_text='Max stipend in ₹'),
        ),
        migrations.AddField(
            model_name='microinternship',
            name='min_salary',
            field=models.PositiveIntegerField(default=0, help_text='Min stipend in ₹'),
        ),
    ]
