# Generated by Django 5.2.3 on 2026-03-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_website_link_userprofile_github_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
