# Generated by Django 5.2.3 on 2026-04-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userprofile_company_name_userprofile_website_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='generated_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hair_type',
            field=models.CharField(choices=[('wavy', 'Wavy'), ('straight', 'Straight'), ('curly', 'Curly'), ('bald', 'Bald')], default='straight', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_specs',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
