# Generated by Django 5.2.3 on 2026-04-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userprofile_generated_avatar_userprofile_hair_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('company', 'Company')], max_length=10, null=True),
        ),
    ]
